spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resume_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

ml:
  service:
    url: http://localhost:8000/analyze